# Generated by Django 4.1.2 on 2022-10-14 07:05

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', ckeditor.fields.RichTextField()),
                ('mini_description', ckeditor.fields.RichTextField()),
                ('category', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=b'I01\n')),
                ('adding_date', models.DateTimeField(default=datetime.datetime.now)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
